services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - customers
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - redis:/data
    networks:
      - customers
  cart:
    image: prospeak15/cart
    container_name: cart
    ports:
      - "4000:4000"
    networks:
      - customers
    depends_on:
      - redis
      - zipkin
    environment:
      - PORT=4000
      - REDIS_HOST=redis://redis:6379
  customer:
    image: prospeak15/customer
    container_name: customer
    ports:
      - "4001:4001"
    networks:
      - customers
    depends_on:
      - postgres
      - zipkin
    environment:
      - PORT=4001
    env_file:
      - .env
  inventory:
    image: prospeak15/inventory
    container_name: inventory
    ports:
      - "4002:4002"
    networks:
      - customers
    depends_on:
      - postgres
      - zipkin
    environment:
      - PORT=4002
    env_file:
      - .env
  apigw:
    image: prospeak15/apigw
    container_name: apigw
    ports:
      - "4003:3000"
    networks:
      - customers
    depends_on:
      - zipkin
networks:
  postgres:
    driver: bridge
  customers:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  redis: