FROM node:lts-alpine

WORKDIR /usr/src/app

RUN apk add libc6-compat
RUN ln -s /lib/libc.musl-x86_64.so.1 /lib/ld-linux-x86-64.so.2

# Copy root package.json and lockfile
COPY *.json ./

# Copy the docs package.json
COPY packages/apigw/package.json ./packages/apigw/package.json
COPY packages/apigw ./packages/apigw

RUN npm install
RUN npm install -w @prospeak/apigw

# Copy app source

EXPOSE 3000

CMD ["npm", "start"]