FROM node:lts-alpine

WORKDIR /usr/src/app

# Copy root package.json and lockfile
COPY *.json ./

# Copy the docs package.json
COPY packages/cart/package.json ./packages/cart/package.json
COPY packages/cart ./packages/cart
COPY prisma ./prisma/

RUN npm install
RUN npm install -w @prospeak/cart
# Copy app source

EXPOSE 3000

CMD [ "node", "packages/cart/lib/index.js" ]