FROM node:lts-alpine

WORKDIR /usr/src/app

# Copy root package.json and lockfile
COPY package.json ./
COPY package-lock.json ./

# Copy the docs package.json
COPY packages/customer/package.json ./packages/customer/package.json

COPY prisma ./prisma/

RUN npm install

# Copy app source
COPY . .

EXPOSE 3000

CMD [ "node", "packages/customer/lib/index.js" ]