FROM node:lts-alpine

WORKDIR /usr/src/app

# Copy root package.json and lockfile
COPY package.json ./
COPY package-lock.json ./

# Copy the docs package.json
COPY packages/inventory/package.json ./packages/inventory/package.json

COPY prisma ./prisma/

RUN npm install
RUN npm install -w @prospeak/inventory
RUN npx lerna run tsc

# Copy app source
COPY packages/inventory ./packages/inventory

EXPOSE 3000

CMD [ "node", "packages/inventory/lib/index.js" ]