FROM node:lts-alpine

WORKDIR /usr/src/app

# Copy root package.json and lockfile
COPY *.json ./

# Copy the docs package.json
COPY packages/inventory/package.json ./packages/inventory/package.json
# Copy app source
COPY packages/inventory ./packages/inventory
COPY prisma ./prisma/

RUN npm install
RUN npm install -w @prospeak/inventory


EXPOSE 3000

CMD [ "node", "packages/inventory/lib/index.js" ]