FROM node:lts-alpine

WORKDIR /usr/src/app

# Copy root package.json and lockfile
COPY package.json ./
COPY package-lock.json ./

# Copy the docs package.json
COPY packages/customer/package.json ./packages/customer/package.json

COPY prisma ./prisma/

RUN npm install
RUN npm install -w @prospeak/customer
RUN npx lerna run tsc

# Copy app source
COPY packages/customer ./packages/customer

EXPOSE 3000

CMD [ "node", "packages/customer/lib/index.js" ]